## array 创建和生成
     
     1、传入list   

In [2]:
import numpy as np


In [2]:
np.array((1,2,3))

array([1, 2, 3])

   2、使用 linspace/logspace 生成

In [4]:
np.linspace(0, 9, 6).reshape(2, 3)

array([[0. , 1.8, 3.6],
       [5.4, 7.2, 9. ]])

⭐3、使用random 生成   常用于神经网络的初始化、随机生成测试数据

In [5]:
# 0-1l连续均匀分布
np.random.rand(2,3)

array([[0.53563891, 0.87044493, 0.07984134],
       [0.85044135, 0.2640534 , 0.85068769]])

In [6]:
#标准正态分布
np.random.randn(2,4)

array([[-1.74691268, -0.68079741,  0.48098039,  0.20683811],
       [-0.79226265,  1.2341618 ,  0.31665079, -0.11509181]])

In [7]:
#高斯分布
np.random.normal(0,1,(3,5))

array([[-0.17849819, -1.01550569,  0.52293846,  0.37389139,  0.52490671],
       [-0.50293242, -0.13985853,  2.06332971, -1.9458232 ,  0.36648421],
       [-0.34187044, -0.59627805,  0.58580132,  0.20272636,  0.01875406]])

## 统计和属性
- 尺寸相关
- 最大、最小、中位、分位值
- 平均、求和、标准差等

两个特性
- 按维度（指定 axis）求结果。一般0表示列1表示行，可以用「**沿着行/列操作**」这样理解，不确定时可以拿个例子试一下。
- 计算后保持维度（`keepdims=True`）

In [11]:
arr=np.random.uniform(0,1,(3,4))

In [12]:
arr

array([[0.00242359, 0.97083515, 0.65598727, 0.5191106 ],
       [0.62931058, 0.82723109, 0.30505808, 0.5843532 ],
       [0.09747276, 0.93091347, 0.23856667, 0.0332754 ]])

In [13]:
arra.shape

(3, 4)

 最大最小 np.max/min

In [14]:
#按维度（行）最大值
arr.max(axis=1)

array([0.97083515, 0.82723109, 0.93091347])

In [16]:
#按行 保持行维度   shape为（3，1）
arr.max(axis=1,keepdims=True)

array([[0.97083515],
       [0.82723109],
       [0.93091347]])

In [17]:
#按维度（行）求和
arr.sum(axis=1)

array([2.14835661, 2.34595295, 1.3002283 ])

## 形状和 转换

### 改变形状
- 扩展1维度 expand_dims 
- 去除1维度 squeeze

In [19]:
rng=np.random.default_rng(seed=40)
arr=rng.integers(1,100,(3,4))
arr

array([[56, 73,  3, 69],
       [44, 94,  4,  6],
       [47, 69,  8, 92]], dtype=int64)

In [29]:
#扩展1个维度
expanded=np.expand_dims(arr,0)
expanded

array([[[56, 73,  3, 69],
        [44, 94,  4,  6],
        [47, 69,  8, 92]]], dtype=int64)

In [28]:
expanded.shape

(1, 3, 4)

np.squeeze 指定的axis的shape必须为1

In [25]:
np.squeeze(expanded, axis=0)

array([[56, 73,  3, 69],
       [44, 94,  4,  6],
       [47, 69,  8, 92]], dtype=int64)

# 分解和组合

## 切片和索引

对已知array进行操作从而得到部分元素。 
按照维度处理，不处理的维度用: 或者...代替
-   逗号，分割维度

In [4]:
rng=np.random.default_rng(42)
arr = rng.integers(0, 20, (5, 4))
arr

array([[ 1, 15, 13,  8],
       [ 8, 17,  1, 13],
       [ 4,  1, 10, 19],
       [14, 15, 14, 15],
       [10,  2, 16,  9]], dtype=int64)

### index/sclice

In [5]:
#取第0行
arr[0]

array([ 1, 15, 13,  8], dtype=int64)

In [6]:
#取第1、3行
arr[[0,3]]

array([[ 1, 15, 13,  8],
       [14, 15, 14, 15]], dtype=int64)

In [7]:
#第一列的值，其实是所有维度第1维的值
arr[...,1]
#也可写成arr[:,1]

array([15, 17,  1, 15,  2], dtype=int64)

### 拼接 对几个array进行拼接以形成大的array
### np.concatenate

In [8]:
arr1 = rng.integers(30, 50, (5, 4))
arr1

array([[40, 37, 33, 48],
       [45, 42, 38, 46],
       [40, 38, 39, 34],
       [31, 41, 47, 31],
       [47, 46, 35, 42]], dtype=int64)

In [9]:
#默认沿着axis=0（列）连接
np.concatenate((arr,arr1))

array([[ 1, 15, 13,  8],
       [ 8, 17,  1, 13],
       [ 4,  1, 10, 19],
       [14, 15, 14, 15],
       [10,  2, 16,  9],
       [40, 37, 33, 48],
       [45, 42, 38, 46],
       [40, 38, 39, 34],
       [31, 41, 47, 31],
       [47, 46, 35, 42]], dtype=int64)

In [10]:
np.concatenate((arr,arr1),axis=1)

array([[ 1, 15, 13,  8, 40, 37, 33, 48],
       [ 8, 17,  1, 13, 45, 42, 38, 46],
       [ 4,  1, 10, 19, 40, 38, 39, 34],
       [14, 15, 14, 15, 31, 41, 47, 31],
       [10,  2, 16,  9, 47, 46, 35, 42]], dtype=int64)